### ISSUE TITLE
BUG: SSL : unsupported protocol

### ISSUE THREAD

**Issue by SunHao-0** [Rrooach/auto_dial#1]
Hello,

Thanks for sharing this script. that's very nice of you.
However, `auto_dial.py` contains many bugs.
For example, the following error occurred after several login attempts.
```
> python3 connect.py --connect
21/10/21 17:20:27 293 [INFO,net_login:36] posting: https://net.tsinghua.edu.cn/do_login.php
21/10/21 17:20:27 372 [INFO,net_login:42] HTTPSConnectionPool(host='net.tsinghua.edu.cn', port=443): Max retries exceeded with url: /do_login.php (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1131)')))
```

Can you take a look?
Thanks! *_*

**Comment by fCorleone** [comment]
I think this is a critical bug. Hope for solutions!!

**Comment by Rrooach** [comment]
It's not a bug, something must be wrong with your PC or your keyborad
